PRINT(CONCAT( 'SYSDATETIME()        ', SYSDATETIME() ))
PRINT(CONCAT( 'SYSDATETIMEOFFSET()  ', SYSDATETIMEOFFSET())  )
PRINT(CONCAT( 'SYSUTCDATETIME()     ', SYSUTCDATETIME() ))
PRINT(CONCAT( 'CURRENT_TIMESTAMP    ', CURRENT_TIMESTAMP ))
PRINT(CONCAT( 'GETDATE()            ', GETDATE() ))
PRINT(CONCAT( 'GETUTCDATE()         ', GETUTCDATE()))


PRINT(CONCAT( 'SYSDATETIME()        ', CONVERT(DATE, SYSDATETIME())))
PRINT(CONCAT( 'SYSDATETIMEOFFSET()  ', CONVERT(DATE, SYSDATETIMEOFFSET())))
PRINT(CONCAT( 'SYSUTCDATETIME()     ', CONVERT(DATE, SYSUTCDATETIME())))
PRINT(CONCAT( 'CURRENT_TIMESTAMP    ', CONVERT(DATE, CURRENT_TIMESTAMP)))
PRINT(CONCAT( 'GETDATE()            ', CONVERT(DATE, GETDATE())))
PRINT(CONCAT( 'GETUTCDATE()         ', CONVERT(DATE, GETUTCDATE())))


PRINT(CONCAT( 'SYSDATETIME()        ', CONVERT(TIME, SYSDATETIME())))
PRINT(CONCAT( 'SYSDATETIMEOFFSET()  ', CONVERT(TIME, SYSDATETIMEOFFSET())))
PRINT(CONCAT( 'SYSUTCDATETIME()     ', CONVERT(TIME, SYSUTCDATETIME())))
PRINT(CONCAT( 'CURRENT_TIMESTAMP    ', CONVERT(TIME, CURRENT_TIMESTAMP)))
PRINT(CONCAT( 'GETDATE()            ', CONVERT(TIME, GETDATE())))
PRINT(CONCAT( 'GETUTCDATE()         ', CONVERT(TIME, GETUTCDATE())))